# This file created by conda-build 3.17.8
# ------------------------------------------------

package:
    name: matplotlib
    version: 3.1.3
source:
    patches:
        - PR14891.patch
        - setupext.patch
    sha256: 6edfe021671fcad1bd6081c980c380cb3d66d00895eb8c3450fa3842c441d1d1
    url: https://github.com/matplotlib/matplotlib/archive/v3.1.3.tar.gz
build:
    noarch: false
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - openssl 1.1.1d he774522_3
        - python 3.7.6 h60c2a47_2
        - sqlite 3.31.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - matplotlib-base 3.1.3 py37h64f37c6_0
        - pyqt
        - python >=3.7,<3.8.0a0
test:
    imports:
        - matplotlib
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
